# Generated by Django 2.2.9 on 2020-01-19 16:45

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200111_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cancellation_policy',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='gtc',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='shipping',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
