# Generated by Django 2.2.9 on 2020-05-13 18:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200512_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='footers',
            field=wagtail.core.fields.StreamField([('f_partners', wagtail.core.blocks.StructBlock([('trusted_partner', wagtail.core.blocks.StreamBlock([('partner', wagtail.core.blocks.StructBlock([('partner_logo', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Image fitting this step', null=True)), ('partner_link', wagtail.core.blocks.URLBlock(blank=True, help_text='Important! Format https://www.domain.tld/xyz', null=True))], blank=True, icon='fa-id-badge', null=True))], blank=False, max_num=4, null=True))], blank=False, icon='fa-id-badge', null=True)), ('s_paymentmethods', wagtail.core.blocks.StructBlock([('trusted_paymentmethods', wagtail.core.blocks.StreamBlock([('paymentmethods', wagtail.core.blocks.StructBlock([('partner_logo', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Image fitting this step', null=True)), ('partner_link', wagtail.core.blocks.URLBlock(blank=True, help_text='Important! Format https://www.domain.tld/xyz', null=True))], blank=True, icon='fa-id-badge', null=True))], blank=False, max_num=4, null=True))], blank=False, icon='fa-credit-card', null=True))], null=True),
        ),
    ]
